Sprint 3
lastmarsch/middle.messenger.praktikum.yandex pull request #3
Opened 2022-07-01 20:53 UTC by lastmarsch

2022-07-02 07:50 UTC, agadoev requested changes
Привет
Спасибо за работу, из сильных моментов могу выделить:
1. Чисто и аккуратно написан слой, отвечающий за HTTP
2. Написаны тесты

Из слабых:
1. Есть дублирование кода
2. В некоторых местах код загрязнен

Поправь те места, которые я отметил и двинемся дальше :)

2022-07-02 07:50 UTC, agadoev commented on src/components/validatedInput/validatedInput.ts
>      const isValid = RegExp(this.props.regexp as string).test(text);
Класс ValidatedInput наследуется от Input, но наследование не всегда является лучшим инструментом переиспользования кода. Например в этой ситуации сложно будет типизировать пропсы для ValidateInput. Подумай, может использовать вместо наследования композицию и HOC?

2022-07-02 07:50 UTC, agadoev commented on src/core/Block.ts
> +    // if (this.element?.parentNode?.nodeType === Node.DOCUMENT_FRAGMENT_NODE) {
Лучше не держать закомментированный код, он загрязняет весь код и отвлекает внимание. Если в будущем тебе он понадобится, ты всегда сможешь посмотреть его в системе контроля версий

2022-07-02 07:50 UTC, agadoev commented on src/core/block.spec.ts
> +    const id = 'test';
дублируется создание тестового блока
Обычно все, что подготавливается перед запуском теста, выносят в методы beforeEach и afterEach. В beforeEach создаются необходимые для тестов сущности, а в afterEach - очищаются

2022-07-02 07:50 UTC, agadoev commented on src/core/render.ts
> +  root!.innerHTML = '';
querySelector может вернуть null и эту ситуацию лучше обработать вручную.

2022-07-02 07:50 UTC, agadoev commented on src/pages/auth/signIn.ts
> +          .catch((e) => console.log(`%c ${e}`, 'background: #c6282850;'));
этот console.log можно вынести в отдельную функцию, например logError и поместить в папку utils. Сейчас много где этот код дублируется

2022-07-02 07:50 UTC, agadoev commented on src/pages/auth/signUp.ts
> +            // console.log('authService.signUp', r);
Ненужный код стоит убрать

2022-07-02 07:50 UTC, agadoev commented on src/pages/chat/chat.ts
>      <div class="${styles['app-container']}">
при использовании css modules предпочтительнее использовать camelCase в названиях классов, потому что так код выглядит чище

[Почитать здесь](https://github.com/css-modules/css-modules)

2022-07-02 07:50 UTC, agadoev commented on src/pages/settings/changeInfo.ts
> +      console.log(data);
Постарайся не оставлять отладочные консоль логи. Когда твой коллега откроет консоль, она будет загрязнена ненужной информацией и это только отвлекает

2022-07-02 07:50 UTC, agadoev commented on src/pages/settings/changePassword.ts
> +      let isValid = true;
Кажется эта логика повторяется в компонентах. Подумай над тем, как можно ее вынести и переиспользовать. Дублирование кода - сигнал о том, что что-то идет не так

2022-07-03 11:11 UTC, lastmarsch commented
Привет, удалила комментарии, вынесла валидацию форм и инпутов в HOC withValidation, добавила функцию logError. Поправила тесты и названия CSS классов.

2022-07-05 09:34 UTC, agadoev commented
Привет)
Спасибо за работу, все поправлено, работу принимаю. Удачи в следующем спринте :)

2022-07-05 09:34 UTC, agadoev approved these changes

2022-07-08 05:05 UTC, merged